### PR TITLE
Go live checklist

### LINKED ISSUE #366: Create go-live on mozilla domain checklist
This should be a checklist we follow whenever hosting something on one of our domains.

### PR DESCRIPTION
**Pull request by cadecairos**
Fixes #366 

This patch adds a go-live checklist document to the repo.

thoughts, additions? 

@alicoding @gideonthomas  @simonwex

### CODE REVIEW

**Comment by alicoding** [comment]
@cadecairos I thought you want to create `ISSUE_TEMPLATE.md` ??

**Comment by cadecairos** [comment]
> I thought you want to create ISSUE_TEMPLATE.md ??

We've already got an Issue Template. I don't think that this needs to go there, people filing issues shouldn't be bothered with these details.

**Comment by cadecairos** [comment]
Any objections/suggestions on the go-live checklist?

**Comment by alicoding** [comment]
r+ from me

**Comment by cadecairos** [comment]
Let's iterate on this.

**Pull request merged**
