### PR TITLE
Deployment Standards docs

### LINKED ISSUE #400: Documentation around deployment standards
It would be nice to get everyone (engineering & otherwise) on the same page with regards to our deployment best practices. Not so much *how* we deploy, but things like:

- Who can deploy
- What times are best for deployment (eg: not Friday)
- What do you do if something goes wrong
- How are people notified?
- Rollback protocol

### PR DESCRIPTION
**Pull request by cadecairos**
Fixes #400

### CODE REVIEW

**Comment by cadecairos** [comment]
@gideonthomas @alicoding Anything you think we should add here?

**Comment by alicoding** [comment]
LGTM

**Comment by cadecairos** [comment]
> LGTM

nuh uh, cause you're on PTO! you couldn't possibly be reviewing changes here.

**Comment by gideonthomas** [comment]
r+

**Pull request merged**
